### ISSUE TITLE
An invalid character in my toml file triggered a discriminant check failed error

### ISSUE THREAD

**Issue by simonjwright** [pmderodat/ada-toml#12]
Please see [this issue](https://github.com/alire-project/alire/issues/1274) raised on Alire.

**Comment by pmderodat** [comment]
Hello @simonjwright, thank you for reporting this! Your description of the problem allowed me to reproduce and thus to fix this bug. :-) I’m going to push the fixlet, please let me know if you have other issues with the parser.
