### ISSUE TITLE
Master is not latest branch

### ISSUE THREAD

**Issue by twodayporkathon** [pmderodat/ada-toml#18]
The Master branch of ada-toml is not the most recent release (v0.4). The Alire repository utility downloads v0.4, suggesting v0.4 should be the production version, not Master. Breaking differences in Master include, for example, 
```
    function Create_String (Value : String; Location : Source_Location) return TOML_Value ... ;
```
In v0.4, `Location` is no longer a parameter, and using it emits
```
    error: unmatched actual "Location" in call
```
My workaround was to clone with
```
    git clone https://github.com/pmderodat/ada-toml.git --branch v0.4
```
Additionally, even in version tagged v0.4, line 12 of `src/todo.ads` is
```
   Version : constant String := "0.1";
```
Solutions are to merge branch v0.4 into Master and update line 12 of `src/todo.ads`.

Thanks to maintainers for making this convenient library available!

**Comment by pmderodat** [comment]
Hello,

Thank you for the kind words :-) I have just created the 0.5.0 release on GitHub and opened https://github.com/alire-project/alire-index/pull/1274 to publish it on Alire.

The rest will happen on that merge request, so I’ll close this issue for now: please let me know if I forgot something!
